/**
 * Direct-sequence spread-spectrum (DS-SS) building blocks.
 * Proakis & Salehi §10.3 (Spread-Spectrum Communication Systems).
 */

/**
 * Maximal-length sequence (m-sequence) of period N = 2^n - 1, generated by a
 * Fibonacci LFSR with a primitive feedback polynomial. Returned as ±1 chips
 * (logical 1 → +1, logical 0 → -1). Proakis §10.3.5. Supported n: 3..7.
 */
export function mSequence(n: number): number[] {
  // Primitive-polynomial tap positions (1-indexed register stages), per n.
  const TAPS: Record<number, number[]> = {
    3: [3, 1],
    4: [4, 1],
    5: [5, 2],
    6: [6, 1],
    7: [7, 1],
  };
  const taps = TAPS[n];
  if (!taps) throw new Error(`mSequence: unsupported register length n=${n} (use 3..7)`);
  const N = (1 << n) - 1;
  const reg = new Array<number>(n).fill(0);
  reg[0] = 1; // any non-zero initial state
  const out: number[] = [];
  for (let i = 0; i < N; i++) {
    out.push(reg[n - 1] === 1 ? 1 : -1);
    let fb = 0;
    for (const tp of taps) fb ^= reg[tp - 1];
    for (let j = n - 1; j > 0; j--) reg[j] = reg[j - 1];
    reg[0] = fb;
  }
  return out;
}

/**
 * Cyclic (periodic) autocorrelation of a ±1 PN sequence:
 *   R(k) = Σ_i c_i · c_{(i+k) mod N}.
 * For an m-sequence this is two-valued: R(0) = N and R(k≠0) = -1.
 */
export function pnAutocorrelation(seq: number[]): number[] {
  const N = seq.length;
  const ac = new Array<number>(N).fill(0);
  for (let k = 0; k < N; k++) {
    let sum = 0;
    for (let i = 0; i < N; i++) sum += seq[i] * seq[(i + k) % N];
    ac[k] = sum;
  }
  return ac;
}
